services:
  api:
    container_name: play-api
    build:
      context: ./api
      dockerfile: dev.Dockerfile
    volumes:
      - ./api/src:/api/src
      - .:/workspace:cached
    ports:
      - 5000:5000
  next-app:
    container_name: play-app
    build:
      context: ./app
      dockerfile: dev.Dockerfile
    volumes:
      - ./app/src:/app/src
      - ./app/public:/app/public
      - .:/workspace:cached
    restart: always
    ports:
      - 3000:3000
